### PR TITLE
Add the README as module documentation

### PR DESCRIPTION
**Pull request by tertsdiepraam**
I included the README as module documentation so that it shows up on docs.rs. Since the tests require more setup, I disabled them.

cc @LHolten

### CODE REVIEW

**Comment by LHolten** [comment]
Thanks @tertsdiepraam :)

**Comment by LHolten** [comment]
It's annoying that I can not hide parts of the code blocks in the readme like in rustdoc.
I think I will use https://github.com/orium/cargo-rdme because it supports checking that the readme is up to date with rustdoc in ci.

**Comment by tertsdiepraam** [comment]
Pretty cool crate!

**Comment by LHolten** [comment]
This PR is no longer necessary because of #9, thanks for the idea!

**Pull request closed without merging**
